# Site settings
title: Roman's Notes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Random notes from my findings and experiments
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: romanukyan
github_username:  romanukyan

# Build settings
markdown: kramdown
